### ISSUE TITLE
Is it possible to reuse the filter after built?

### ISSUE THREAD

**Issue by Dan-Do** [FastFilter/xor_singleheader#34]
Let say I have 1 million items. After the filter is built, it's saved to disk. Later I have some more items, can I reload the saved filter the incrementally add items without building the filter from scratch?
As far as I know, bloom filter can do that.

**Comment by lemire** [comment]
>  Later I have some more items, can I reload the saved filter the incrementally add items without building the filter from scratch?

The filter is constructed with full capacity: there is no empty space where you can add extra elements. So Yyu should rebuild the filter if you wish to add elements to your set.

> As far as I know, bloom filter can do that.

To a point, yes. The Bloom filter has a given capacity. You can add elements to it, and this will progressively increase the false-positive probability. Furthermore, if you seek optimal storage given the false-positive rate, you should construct the Bloom filters with the right number of hash functions and storage, otherwise you will have suboptimal efficiency.
