### ISSUE TITLE
Fingerprinting function

### ISSUE THREAD

**Issue by BaiqingL** [FastFilter/xor_singleheader#40]
In the paper, I read that the fingerprint function `maps each possible value from the universe to a word value`, I wanted to see how that's implemented here and found:

https://github.com/FastFilter/xor_singleheader/blob/177cf03e8573519a86f4fb34a626b619947d431d/include/binaryfusefilter.h#L394-L396

What is the reasoning for this? I am a bit confused at how we arrived at this function.

Thanks!

**Comment by lemire** [comment]
@thomasmueller You want to take this question?

**Comment by thomasmueller** [comment]
Yes, so this function is used to map each hash value to a fingerprint:

```
static inline uint64_t binary_fuse16_fingerprint(uint64_t hash) {
  return hash ^ (hash >> 32);
}
```

You didn't write why this confused you, but I can see two possible reasons:
* Why is it so complicated and use `hash ^ (hash >> 32)`
* Why does it return `uint64_t` and not `uint16_t`?

The reason for the complication is that `hash` is used for multiple things, one is to calculate the fingerprint and the other is to calculate the 3 locations. We need to ensure the fingerprint and the location are as unrelated as possible from each other. Otherwise the false positive rate would be slightly worse than it is. The fastest way to achieve this by using a simple "supplemental hash" function. Here we hash the hash value again. Another option would be to use a more complex way, but that would be slower. We found that `hash ^ (hash >> 32)` is necessary, and sufficient. Supplemental hash functions are used, for similar reasons, in other libraries, for example in the Java standard library, for the HashMap class:

https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/util/HashMap.java#L268

```
   /**
     * Applies a supplemental hash function to a given hashCode, which
     * defends against poor quality hash functions.  This is critical
     * because HashMap uses power-of-two length hash tables, that
     * otherwise encounter collisions for hashCodes that do not differ
     * in lower bits. Note: Null keys always map to hash 0, thus index 0.
     */
    static int hash(int h) {
        // This function ensures that hashCodes that differ only by
        // constant multiples at each bit position have a bounded
        // number of collisions (approximately 8 at default load factor).
        h ^= (h >>> 20) ^ (h >>> 12);
        return h ^ (h >>> 7) ^ (h >>> 4);
    }

```

(In previous versions of Java, the method was different).

The reason to return `uint64_t`:

This method is called in two place; one is the construction, and one is the lookup ("contain" method):

```
// Report if the key is in the set, with false positive rate.
static inline bool binary_fuse16_contain(uint64_t key,
                                        const binary_fuse16_t *filter) {
  uint64_t hash = binary_fuse_mix_split(key, filter->Seed);
  uint16_t f = binary_fuse16_fingerprint(hash); 
  binary_hashes_t hashes = binary_fuse16_hash_batch(hash, filter);
  f ^= filter->Fingerprints[hashes.h0] ^ filter->Fingerprints[hashes.h1] ^
       filter->Fingerprints[hashes.h2];
  return f == 0;
}
```

In both cases, it is converted to uint16_t. We could change the method to return uint16_t, that would also work -- it might be a bit easier to read and understand for a human, but it wouldn't make a difference in the execution. Or we could add a comment.

**Comment by thomasmueller** [comment]
I hope this was useful. If might make sense to add a comment or two in the source code; but then, we would probably need to add a lot of comments...

**Comment by lemire** [comment]
It was very well explained.
